AIServicesDemoApp/Pages/AnalyzeDocument.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using Amazon.Textract;
using Amazon.Textract.Model;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;

namespace AIServicesDemoApp.Pages
{
    public class AnalyzeDocumentModel(IAmazonTextract textractClient, IWebHostEnvironment hostEnvironment)
        : PageModel
    {
        [BindProperty]
        public IFormFile? FormFile { get; set; }
        public string FileName { get; set; } = string.Empty;
        public string Result { get; set; } = string.Empty;

        public void OnGet()
        {
        }
        
        public async Task OnPostDetectTextAsync()
        {
            if (FormFile == null)
            {
                return;
            }
            // save document image to display it
            var formDocument = await Helpers.SaveImage(FormFile, hostEnvironment.WebRootPath);
            FileName = formDocument.FileName;

            var detectDocumentTextRequest = new DetectDocumentTextRequest()
            {
                Document = new Document { Bytes = formDocument.MemoryStream }
            };

            var detectDocumentTextResponse = await textractClient.DetectDocumentTextAsync(detectDocumentTextRequest);

            var stringBuilder = new StringBuilder();

            // Load image to modify with face bounding box rectangle
            using (var image = await SixLabors.ImageSharp.Image.LoadAsync(formDocument.FileNameWithPath))
            {
                foreach (var block in detectDocumentTextResponse.Blocks)
                {
                    if (block.BlockType.Value == "LINE")
                    {
                        stringBuilder.AppendFormat("{0}<br>", block.Text);

                        // Get the bounding box
                        var boundingBox = block.Geometry.BoundingBox;

                        // Draw the rectangle using the bounding box values
                        image.DrawRectangleUsingBoundingBox(boundingBox);
                    }
                }

                // Save the new image
                await image.SaveAsJpegAsync(formDocument.FileNameWithPath, new JpegEncoder { ColorType = JpegEncodingColor.Rgb});
            }
            
            Result = stringBuilder.ToString();
        }

        public async Task OnPostDetectFormsAsync()
        {
            if (FormFile == null)
            {
                return;
            }
            // save document image to display it
            var formDocument = await Helpers.SaveImage(FormFile, hostEnvironment.WebRootPath);
            FileName = formDocument.FileName;

            var analyzeDocumentRequest = new AnalyzeDocumentRequest
            {
                Document = new Document { Bytes = formDocument.MemoryStream },
                FeatureTypes = ["FORMS"]
            };

            var analyzeDocumentResponse = await textractClient.AnalyzeDocumentAsync(analyzeDocumentRequest);

            var stringBuilder = new StringBuilder();

            // Load image to modify with face bounding box rectangle
            using (var image = await SixLabors.ImageSharp.Image.LoadAsync(formDocument.FileNameWithPath))
            {
                foreach (var block in analyzeDocumentResponse.Blocks)
                {
                    if (block.BlockType.Value == "KEY_VALUE_SET")
                    {
                        foreach (var relation in block.Relationships)
                        {
                            if (relation.Type == RelationshipType.CHILD) {
                                foreach (var id in relation.Ids)
                                {
                                    var related = analyzeDocumentResponse.Blocks.First(b => b.Id == id);

                                    stringBuilder.AppendFormat("{0} ", related.Text);    
                                }
                            }
                            
                            stringBuilder.AppendFormat("<br>");    
                        }
                        
                        // Get the bounding box
                        var boundingBox = block.Geometry.BoundingBox;

                        // Draw the rectangle using the bounding box values
                        image.DrawRectangleUsingBoundingBox(boundingBox);
                    }
                }

                // Save the new image
                await image.SaveAsJpegAsync(formDocument.FileNameWithPath, new JpegEncoder { ColorType = JpegEncodingColor.Rgb});
            }

            Result = stringBuilder.ToString();
        }
        
        public async Task OnPostDetectTablesAsync()
        {
            if (FormFile == null)
            {
                return;
            }
            // save document image to display it
            var formDocument = await Helpers.SaveImage(FormFile, hostEnvironment.WebRootPath);
            FileName = formDocument.FileName;

            var analyzeDocumentRequest = new AnalyzeDocumentRequest
            {
                Document = new Document { Bytes = formDocument.MemoryStream },
                FeatureTypes = ["TABLES"]
            };

            var analyzeDocumentResponse = await textractClient.AnalyzeDocumentAsync(analyzeDocumentRequest);

            var stringBuilder = new StringBuilder();

            // Load image to modify with face bounding box rectangle
            using (var image = await SixLabors.ImageSharp.Image.LoadAsync(formDocument.FileNameWithPath))
            {
                foreach (var block in analyzeDocumentResponse.Blocks)
                {
                    if (block.BlockType.Value == "TABLE")
                    {
                        // Get the bounding box
                        var boundingBox = block.Geometry.BoundingBox;

                        // Draw the rectangle using the bounding box values
                        image.DrawRectangleUsingBoundingBox(boundingBox);
                    }
                }

                // Save the new image
                await image.SaveAsJpegAsync(formDocument.FileNameWithPath, new JpegEncoder { ColorType = JpegEncodingColor.Rgb});
            }

            Result = stringBuilder.ToString();
        }
       
    }
}

AIServicesDemoApp/Pages/CustomClassification.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Amazon.Comprehend;
using Amazon.Comprehend.Model;
using Amazon.SecurityToken;
using Amazon.SecurityToken.Model;
using Amazon.Textract;
using Amazon.Textract.Model;

namespace AIServicesDemoApp.Pages
{
    public class CustomClassificationModel(IAmazonComprehend comprehendClient, IAmazonTextract textractClient,
            IWebHostEnvironment hostEnvironment)
        : PageModel
    {
        public string Result { get; set; } = string.Empty;

        // TODO: use your bucket name
        private const string BUCKET_NAME = "adrag-idp";
        private const string DOCUMENT_CLASSIFIER_NAME = "ReInvent-IDP-Insurance-Demo-Doc-Classifier";
        private const string DOCUMENT_CLASSIFIER_VERSION = "IDP-v1";
        private const string DOCUMENT_CLASSIFIER_ENDPOINT_NAME = "ReInvent-IDP-Insurance-Demo-Endpoint";

        public void OnGet()
        {
        }

        private async Task<string> GetDocumentLines(string documentKey)
        {
            var request = new DetectDocumentTextRequest
            {
                Document = new Document
                {
                    S3Object = new S3Object
                    {
                        Bucket = BUCKET_NAME,
                        Name = documentKey
                    }
                }
            };
            var response = await textractClient.DetectDocumentTextAsync(request);
            
            var lines = new StringBuilder();
            foreach (var block in response.Blocks)
            {
                if (block.BlockType == Amazon.Textract.BlockType.LINE)
                {
                    lines.Append($"{block.Text}\n");
                }
            }
            
            return lines.ToString();
        }

        public async Task OnPostPrepareDataAsync()
        {
            var csvFileName = "classifier-training.csv";
            var fullCsvFileName = System.IO.Path.Combine(hostEnvironment.WebRootPath, "uploads", csvFileName);
            
            var s3 = new Amazon.S3.AmazonS3Client();
            
            // check if training CSV already exists
            if (!System.IO.File.Exists(fullCsvFileName))
            {
                var csv = new StringBuilder();
                
                // list files in S3 bucket
                var listRequest = new Amazon.S3.Model.ListObjectsRequest
                {
                    BucketName = BUCKET_NAME,
                    Prefix = "classification-training"
                };
                var listResponse = await s3.ListObjectsAsync(listRequest);
                var files = listResponse.S3Objects.Select(x => x.Key);
                foreach (var file in files)
                {
                    Console.WriteLine($"Processing file: {file}");

                    var lines = await GetDocumentLines(file);
                    lines = lines.Replace('"', '\'');

                    if (file.StartsWith("classification-training/receipts/"))
                    {
                        csv.AppendLine($"receipt,\"{lines}\"");
                    }
                    else if (file.StartsWith("classification-training/bank-statements/"))
                    {
                        csv.AppendLine($"bank-statement,\"{lines}\"");
                    }
                    else if (file.StartsWith("classification-training/invoices/"))
                    {
                        csv.AppendLine($"invoice,\"{lines}\"");
                    }
                }

                // save file to disk (not to generate again)
                using (var stream = new FileStream(fullCsvFileName, FileMode.Create))
                {
                    var bytes = Encoding.UTF8.GetBytes(csv.ToString());
                    await stream.WriteAsync(bytes, 0, bytes.Length);
                }
                
            }

            // upload training CSV to S3 bucket
            var putRequest = new Amazon.S3.Model.PutObjectRequest
            {
                BucketName = BUCKET_NAME,
                Key = csvFileName,
                FilePath = fullCsvFileName,
                
            };
            await s3.PutObjectAsync(putRequest);

        }

        public async Task OnPostCreateClassifierAsync()
        {             
            var client = new AmazonSecurityTokenServiceClient();
            var response = await client.GetCallerIdentityAsync(new GetCallerIdentityRequest()); 
            var account = response.Account;
            
            var dataAccessRoleArn = $"arn:aws:iam::{account}:role/service-role/AmazonComprehendServiceRole-IDP-access-S3"; // give access to list/read from S3 bucket

            var classifiers = await comprehendClient.ListDocumentClassifierSummariesAsync(new ListDocumentClassifierSummariesRequest());
            // check if classifier not already exists
            if (!classifiers.DocumentClassifierSummariesList.Exists(classifier => classifier.DocumentClassifierName == DOCUMENT_CLASSIFIER_NAME))
            {
                // create new classifier
                var classifierRequest = new CreateDocumentClassifierRequest
                {
                    LanguageCode = "en",
                    Mode = DocumentClassifierMode.MULTI_CLASS,
                    DocumentClassifierName = DOCUMENT_CLASSIFIER_NAME,
                    VersionName = DOCUMENT_CLASSIFIER_VERSION,
                    DataAccessRoleArn = dataAccessRoleArn,
                    InputDataConfig = new DocumentClassifierInputDataConfig
                    {
                        DataFormat = DocumentClassifierDataFormat.COMPREHEND_CSV,
                        //S3Uri = $"s3://{BUCKET_NAME}/classifier-training.csv"
                        S3Uri = $"s3://{BUCKET_NAME}/insurance_comprehend_train_data.csv"
                    }
                };
                var classifierResponse = await comprehendClient.CreateDocumentClassifierAsync(classifierRequest);
                var classifierArn = classifierResponse.DocumentClassifierArn; // can be used to check status of the training job
            }
            else
            {
                var modelArn = "arn:aws:comprehend:eu-west-1:" + account + ":document-classifier/" + DOCUMENT_CLASSIFIER_NAME + "/version/" + DOCUMENT_CLASSIFIER_VERSION;
                // classifier already exists, create real-time endpoint, if does not exist
                var endpoints = await comprehendClient.ListEndpointsAsync(new ListEndpointsRequest());
                if (!endpoints.EndpointPropertiesList.Exists(endpoint => endpoint.ModelArn == modelArn))
                {
                    // create endpoint
                    var createEndpointRequest = new CreateEndpointRequest
                    {
                        DesiredInferenceUnits = 1,
                        DataAccessRoleArn = dataAccessRoleArn,
                        ModelArn = modelArn,
                        EndpointName = DOCUMENT_CLASSIFIER_ENDPOINT_NAME
                    };
                    await comprehendClient.CreateEndpointAsync(createEndpointRequest);
                }
            }
        }
    }
}

AIServicesDemoApp/Pages/DetectPII.cshtml.cs
using System.Net.Mime;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using Amazon;
using Amazon.BedrockRuntime;
using Amazon.BedrockRuntime.Model;
using Amazon.Comprehend;
using Amazon.Comprehend.Model;
using Amazon.Textract;
using Amazon.Textract.Model;

namespace AIServicesDemoApp.Pages
{
    public class DetectPIIModel(IAmazonTextract textractClient, IAmazonComprehend comprehendClient,
            IWebHostEnvironment hostEnvironment)
        : PageModel
    {
        [BindProperty]
        public IFormFile? FormFile { get; set; }
        public string FileName { get; set; } = string.Empty;
        public string Result { get; set; } = string.Empty;

        public void OnGet()
        {
        }
        
        
        public async Task OnPostDetectPIIAsync()
        {
            if (FormFile == null)
            {
                return;
            }
            // save document image to display it
            var formDocument = await Helpers.SaveImage(FormFile, hostEnvironment.WebRootPath);
            FileName = formDocument.FileName;
            
            // get all text from the document
 
            var request = new DetectDocumentTextRequest
            {
                Document = new Document { Bytes = formDocument.MemoryStream }
            };
            var response = await textractClient.DetectDocumentTextAsync(request);
            var blocks = response.Blocks;
                
            // extract all lines from the text
            var lines = blocks.Where(block => block.BlockType.Value == "LINE")
                .Select(block => block.Text).ToList();
            var text = string.Join("\n", lines);
            
            // detect PII entities
            var detectEntitiesRequest = new DetectPiiEntitiesRequest
            {
                Text = text,
                LanguageCode = "en"
            };
            var detectEntitiesResponse = await comprehendClient.DetectPiiEntitiesAsync(detectEntitiesRequest);
            var entities = detectEntitiesResponse.Entities;
            // display the list
 
            var sb = new StringBuilder();
            foreach (var entity in entities)
            {
                if (entity.BeginOffset.HasValue && entity.EndOffset.HasValue)
                {
                    sb.AppendLine($"Score: {entity.Score}, Type: {entity.Type},");
                    sb.AppendLine($"Text: {text.Substring(entity.BeginOffset.Value, entity.EndOffset.Value - entity.BeginOffset.Value)} <br>");
                }
            }

            Result = sb.ToString();
        }
        
        public async Task OnPostDetectPIIBedrockAsync()
        {
            if (FormFile == null)
            {
                return;
            }
            // save document image to display it
            var formDocument = await Helpers.SaveImage(FormFile, hostEnvironment.WebRootPath);
            FileName = formDocument.FileName;
            
            var runtime = new AmazonBedrockRuntimeClient(RegionEndpoint.USEast1);

            var request = new ConverseRequest
            {
                ModelId = "anthropic.claude-3-sonnet-20240229-v1:0",
                Messages = [
                    new Message
                    {
                        Role = ConversationRole.User,
                        Content = [
                            new ContentBlock
                            {
                                Text = $"Detect all PII information, output list of found entities as JSON with value and type of PII"

                            },
                            new ContentBlock
                            {
                                Image = new ImageBlock
                                {
                                    Format = ImageFormat.Jpeg,
                                    Source = new ImageSource
                                    {
                                        Bytes = formDocument.MemoryStream
                                    }
                                }
                            }
                        ]
                    }
                ]
            };
            
            var response = await runtime.ConverseAsync(request);


            Result = response.Output.Message.Content[0].Text;
            
        }
       
    }
}

AIServicesDemoApp/Pages/AnalyzeDocument.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AnalyzeDocumentModel
@{
    ViewData["Title"] = "Analyze Document";
}

<div>
    <h2 class="display-4">Analyze Document</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">Document:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectText" value="Detect text" />
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectTables" value="Detect tables" />
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectForms" value="Detect forms" />
        </div>
    </form>
    
    <div class="container">
            <div class="row">
                <div class="col-6 pt-3">
                    @if (!string.IsNullOrEmpty(Model.FileName))
                    {
                        <img class="w-100" src="uploads/@Model.FileName" />
                    }
                </div>
                <div class="col-6 pt-3">
                    @Html.Raw(Model.Result)
                </div>
            </div>
        </div>

</div>

AIServicesDemoApp/Pages/AnalyzeExpense.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AnalyzeExpenseModel
@{
    ViewData["Title"] = "Invoice reporting";
}

<div>
    <h2 class="display-4">Invoice reporting</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">Receipt image:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" value="Submit invoice" class="btn btn-primary" />
        </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-6 pt-3">
                @if (!string.IsNullOrEmpty(Model.FileName))
                {
                    <img class="w-100" src="uploads/@Model.FileName" />
                }
            </div>
            <div class="col-6 pt-3">
                @Html.Raw(Model.Result)
            </div>
        </div>
    </div>

</div>

AIServicesDemoApp/Pages/AnalyzeID.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AnalyzeIDModel
@{
    ViewData["Title"] = "Analyze ID";
}

<div>
    <h2 class="display-4">Analyze ID</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">ID image:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" value="Submit ID" class="btn btn-primary" />
        </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-6 pt-3">
                @if (!string.IsNullOrEmpty(Model.FileName))
                {
                    <img class="w-100" src="uploads/@Model.FileName" />
                }
            </div>
            <div class="col-6 pt-3">
                @Html.Raw(Model.Result)
            </div>
        </div>
    </div>

</div>

AIServicesDemoApp/Pages/CustomClassification.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CustomClassificationModel
@{
    ViewData["Title"] = "Document Classification - Custom classification";
}

<div>
    <h2 class="display-4">Custom Classification</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="PrepareData" value="1 - Prepare training data" />
            <input type="submit" class="btn btn-primary" asp-page-handler="CreateClassifier" value="2 - Create classifier" />
        </div>
    </form>
    
    <div class="container">
            <div class="row">
                <div class="col-6 pt-3">
                    @Html.Raw(Model.Result)
                </div>
            </div>
        </div>

</div>

AIServicesDemoApp/Pages/DetectPII.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model DetectPIIModel
@{
    ViewData["Title"] = "Detect PII";
}

<div>
    <h2 class="display-4">Detect PII</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">Document:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectPII" value="Detect PII (AI)" />
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectPIIBedrock" value="Detect PII (GenAI)" />
        </div>
    </form>
    
    <div class="container">
            <div class="row">
                <div class="col-6 pt-3">
                    @if (!string.IsNullOrEmpty(Model.FileName))
                    {
                        <img class="w-100" src="uploads/@Model.FileName" />
                    }
                </div>
                <div class="col-6 pt-3">
                    @Html.Raw(Model.Result)
                </div>
            </div>
        </div>

</div>

AIServicesDemoApp/Pages/DetectSignatures.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model DetectSignaturesModel
@{
    ViewData["Title"] = "Detect Signatures";
}

<div>
    <h2 class="display-4">Detect Signatures</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">Document:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectSignatures" value="Detect Signatures" />
        </div>
    </form>
    
    <div class="container">
            <div class="row">
                <div class="col-12 pt-3">
                    @if (!string.IsNullOrEmpty(Model.FileName))
                    {
                        <img class="w-100" src="uploads/@Model.FileName" />
                    }
                </div>
                
            </div>
        </div>

</div>

AIServicesDemoApp/Pages/DocumentClassification.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model DocumentClassificationModel
@{
    ViewData["Title"] = "Document Classification";
}

<div>
    <h2 class="display-4">Document Classification</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="FormFile" class="control-label">Document:</label>
            <input asp-for="FormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectDocumentType" value="Detect document type (AI)" />
            <input type="submit" class="btn btn-primary" asp-page-handler="DetectDocumentTypeBedrock" value="Detect document type (GenAI)" />
        </div>
    </form>
    
    <div class="container">
            <div class="row">
                <div class="col-6 pt-3">
                    @if (!string.IsNullOrEmpty(Model.FileName))
                    {
                        <img class="w-100" src="uploads/@Model.FileName" />
                    }
                </div>
                <div class="col-6 pt-3">
                    @Html.Raw(Model.Result)
                </div>
            </div>
        </div>

</div>

AIServicesDemoApp/Pages/Identity.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IdentityCheckModel
@{
    ViewData["Title"] = "IdentityCheck";
}

<div>
    <h2 class="display-4">Identity check</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="IdentityFormFile" class="control-label">ID:</label>
            <input asp-for="IdentityFormFile" class="form-control" type="file" />
        </div>
        <div class="form-group">
            <label asp-for="PhotoFormFile" class="control-label">Photo:</label>
            <input asp-for="PhotoFormFile" class="form-control" type="file" />
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" asp-page-handler="Identities" value="Identity Check" />
            <input type="submit" class="btn btn-primary" asp-page-handler="IdentitiesBedrock" value="Identity Check (Bedrock)" />
        </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-6 pt-3">
                @if (!string.IsNullOrEmpty(Model.IdentityFileName))
                {
                    <img class="w-100" src="uploads/@Model.IdentityFileName" />
                }
            </div>
            <div class="col-6 pt-3">
                @Html.Raw(Model.Result)
                @if (!string.IsNullOrEmpty(Model.PhotoFileName))
                {
                    <img class="w-100" src="uploads/@Model.PhotoFileName" />
                }
            </div>
        </div>
    </div>

</div>

AIServicesDemoApp/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div>
    <h2 class="display-4">Let's translate text</h2>

    <p class="gap-1">
        <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Sample texts
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <h4>About AWS Lambda (in French)</h4>
            <p>
                AWS Lambda est un service de calcul sans serveur qui exécute votre code en réponse à des événements et gère automatiquement les ressources de calcul sous-jacentes pour vous. Ces événements peuvent inclure des changements d'état ou une mise à jour, comme un utilisateur plaçant un élément dans un panier sur un site web de e-commerce. Vous pouvez utiliser AWS Lambda pour étendre les autres services AWS avec une logique personnalisée ou créer vos propres services backend qui fonctionnent en bénéficiant de la mise à l’échelle, des performances et de la sécurité AWS. AWS Lambda exécute automatiquement un code en réponse à plusieurs événements, tels que les requêtes HTTP via Amazon API Gateway, les modifications d'objets dans des compartiments Amazon Simple Storage Service (Amazon S3), les mises à jour de tables dans Amazon DynamoDB ou les transitions d'états dans AWS Step Functions.
            </p>
            <h4>About Amazon EC2 (in Portuguese)</h4>
            <p>
                O Amazon Elastic Compute Cloud (Amazon EC2) oferece a plataforma de computação mais ampla e profunda, com mais de 500 instâncias e opções do processador, armazenamento, redes, sistema operacional e modelo de compra mais recentes para ajudar você a atender melhor às necessidades da sua workload. Somos o primeiro grande provedor de nuvem a oferecer suporte para processadores Intel, AMD e Arm, a única nuvem com instâncias Mac do EC2 sob demanda e a única nuvem com redes Ethernet de 400 Gbps. Oferecemos a melhor performance de preço para treinamento de machine learning, bem como o menor custo por instâncias de inferência na nuvem. Mais workloads SAP, computação de alta performance (HPC), ML e Windows são executadas na AWS do que qualquer outra nuvem.
            </p>

        </div>
    </div>


    
    
    <form method="post">
        <div class="form-group pt-3">
            <label for="Text">Text:</label>
            <textarea class="form-control" id="Text" name="Text" rows="5">@Model.Text</textarea>
        </div>
        <div class="form-group pt-3">
            @*<input type="submit" class="btn btn-primary" asp-page-handler="Entities" value="Detect entities" />
            <input type="submit" class="btn btn-primary" asp-page-handler="PII" value="Detect PII" />*@
            <input type="submit" class="btn btn-primary" asp-page-handler="Translate" value="Translate text" />
            <input type="submit" class="btn btn-primary" asp-page-handler="ClaudeTranslate" value="Claude Translate" />
            <input type="submit" class="btn btn-primary" asp-page-handler="LlamaTranslate" value="Llama Translate" />
            <input type="submit" class="btn btn-primary" asp-page-handler="ConverseTranslate" value="Converse Translate" />
            <input type="submit" class="btn btn-primary" asp-page-handler="SKTranslate" value="SK Translate" />
        </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col pt-3">
                @Html.Raw(Model.Result)
            </div>
        </div>
    </div>

</div>